// Music registry generator.
//
// Run: pnpm gen-music (from repo root)
//
// Reads audio files from `public/music/` and writes a fully-regenerated
// `src/canvas/music/registry.ts`. Each file becomes one entry in
// `MUSIC_TRACKS`:
//   - `id`:    filename without extension
//   - `label`: prettified basename (dashes/underscores → spaces, capitalized)
//   - `src`:   public path "/music/<filename>"
//
// The `'none'` sentinel ("Silencio") is hardcoded at the top of the
// registry so the audio engine can always mount silence.
//
// Supported extensions: .mp3 .ogg .wav .m4a .webm.
//
// After running, review the diff before committing — the registry file is
// auto-generated and should not be hand-edited.

import { existsSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const REPO_ROOT = join(import.meta.dirname, '..', '..', '..');
const MUSIC_DIR = join(REPO_ROOT, 'public/music');
const REGISTRY_PATH = join(REPO_ROOT, 'src/canvas/music/registry.ts');

const AUDIO_EXTS = ['mp3', 'ogg', 'wav', 'm4a', 'webm'] as const;
type AudioExt = (typeof AUDIO_EXTS)[number];

function isAudioExt(s: string): s is AudioExt {
  return (AUDIO_EXTS as readonly string[]).includes(s);
}

/**
 * Prettify a filename for the human-readable label. Replaces `-` and `_`
 * with spaces and capitalises the first letter of every word.
 *
 * Uses `\p{L}` (Unicode letter) for the character class, but the boundary
 * detection is hand-rolled because `\b` is defined in terms of ASCII `\w`
 * and would otherwise fire at every accented character — turning
 * `exploración` into `ExploraciÓN`. We capture `(^|\s)(\p{L})` instead,
 * which means "letter at the start of the string or right after a space".
 */
function prettifyBasename(name: string): string {
  return name
    .replace(/[-_]/g, ' ')
    .replace(/(^|\s)(\p{L})/gu, (_, space, letter) => space + letter.toUpperCase());
}

/**
 * Emit a string as a single-quoted JS literal. Falls back to double
 * quotes only when the value contains a single quote (to avoid escaping
 * noise). All other special characters (newlines, backslashes, unicode)
 * are escaped via `JSON.stringify` so the output is always valid JS.
 */
function jsString(s: string): string {
  if (s.includes("'")) return JSON.stringify(s);
  return `'${s}'`;
}

async function main(): Promise<void> {
  if (!existsSync(MUSIC_DIR)) {
    console.error(`✗ Music dir not found: ${MUSIC_DIR}`);
    process.exit(1);
  }

  const entries = readdirSync(MUSIC_DIR);
  const seenIds = new Set<string>();
  const tracks: { id: string; label: string; src: string }[] = [];

  for (const file of entries) {
    // Skip dotfiles — they're OS metadata or hidden scratch, not tracks.
    if (file.startsWith('.')) continue;

    const ext = file.split('.').pop()!.toLowerCase();
    if (!isAudioExt(ext)) continue;

    const id = file.replace(/\.[^.]+$/, '');
    if (id.length === 0) continue; // e.g. ".mp3" — skip silently

    if (seenIds.has(id)) {
      throw new Error(`Duplicate track id "${id}" — filenames must differ beyond extension.`);
    }
    seenIds.add(id);

    const fullPath = join(MUSIC_DIR, file);
    const stats = statSync(fullPath);
    if (!stats.isFile()) continue;
    if (stats.size === 0) {
      throw new Error(`Empty audio file: ${file}`);
    }

    tracks.push({
      id,
      label: prettifyBasename(id),
      src: `/music/${file}`,
    });
  }

  tracks.sort((a, b) => a.id.localeCompare(b.id));

  // Build the track-entry block. When `tracks` is empty we leave only the
  // hardcoded sentinel; otherwise we emit one entry per line, alphabetised.
  // Multi-line shape keeps biome-format happy at 100-col without line wraps.
  const trackBlock =
    tracks.length === 0
      ? ''
      : `\n${tracks
          .map(
            (t) =>
              `  {\n    id: ${jsString(t.id)},\n    label: ${jsString(t.label)},\n    src: ${jsString(t.src)},\n  },`,
          )
          .join('\n')}\n`;

  const content = `// Auto-generated by src/assets/scripts/generate-music-registry.ts.
// Run \`pnpm gen-music\` after adding or removing tracks.
//
// The \`'none'\` sentinel at the top is hardcoded — silence is always
// available. Real tracks are derived from files in \`public/music/\`:
//   - \`id\`:    filename without extension
//   - \`label\`: prettified basename (dashes/underscores → spaces, capitalized)
//   - \`src\`:   public path

export type MusicDef = {
  id: string;
  label: string;
  /** URL of the audio file. \`null\` means "silence — don't mount audio". */
  src: string | null;
};

export const MUSIC_TRACKS: readonly MusicDef[] = [
  // Silence is always available so the user can mute without un-mounting
  // the popover. It's the default selection.
  { id: 'none', label: 'Silencio', src: null },
${trackBlock}] as const;

export function getMusic(id: string): MusicDef {
  return MUSIC_TRACKS.find((m) => m.id === id) ?? MUSIC_TRACKS[0]!;
}
`;

  writeFileSync(REGISTRY_PATH, content, 'utf-8');

  console.log(`\n✓ Generated ${tracks.length} track(s) → ${relative(REPO_ROOT, REGISTRY_PATH)}`);
  if (tracks.length === 0) {
    console.log('  (no audio files yet — only the silence sentinel is registered)');
  } else {
    for (const t of tracks) {
      console.log(`  • ${t.id} → ${t.label}`);
    }
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
