'use server';

import createAction from '@/lib/server/actions/createAction';
import { pieceUseCases } from '@/lib/server/useCases';

/**
 * Cached piece catalog. The catalog is regenerated by `pnpm gen-cat` and is
 * treated as build-time static data; `'use cache'` keeps the React tree from
 * re-serialising it on every request.
 *
 * Lived on `subdivision.action.ts` historically because pieces and subdivisions
 * are both globally-scoped domain data; now that subdivision CRUD is gone we
 * move this here so deleting `subdivision.action.ts` doesn't take the pieces
 * catalog with it.
 */
export const listAllPieces = createAction(null, async () => pieceUseCases.getAllPieces());
