// Auto-generated by src/assets/scripts/generate-music-registry.ts.
// Run `pnpm gen-music` after adding or removing tracks.
//
// The `'none'` sentinel at the top is hardcoded — silence is always
// available. Real tracks are derived from files in `public/music/`:
//   - `id`:    filename without extension
//   - `label`: prettified basename (dashes/underscores → spaces, capitalized)
//   - `src`:   public path

export type MusicDef = {
  id: string;
  label: string;
  /** URL of the audio file. `null` means "silence — don't mount audio". */
  src: string | null;
};

export const MUSIC_TRACKS: readonly MusicDef[] = [
  // Silence is always available so the user can mute without un-mounting
  // the popover. It's the default selection.
  { id: 'none', label: 'Silencio', src: null },

  {
    id: 'batalla-heroica',
    label: 'Batalla Heroica',
    src: '/music/batalla-heroica.mp3',
  },
  {
    id: 'bosque-encantado',
    label: 'Bosque Encantado',
    src: '/music/bosque-encantado.mp3',
  },
  {
    id: 'bosque-maldito',
    label: 'Bosque Maldito',
    src: '/music/bosque-maldito.mp3',
  },
  {
    id: 'caravana',
    label: 'Caravana',
    src: '/music/caravana.mp3',
  },
  {
    id: 'catacumbas',
    label: 'Catacumbas',
    src: '/music/catacumbas.mp3',
  },
  {
    id: 'ciudad-medieval',
    label: 'Ciudad Medieval',
    src: '/music/ciudad-medieval.mp3',
  },
  {
    id: 'descanso',
    label: 'Descanso',
    src: '/music/descanso.mp3',
  },
  {
    id: 'exploración-aventura',
    label: 'Exploración Aventura',
    src: '/music/exploración-aventura.mp3',
  },
  {
    id: 'exploración-calma',
    label: 'Exploración Calma',
    src: '/music/exploración-calma.mp3',
  },
  {
    id: 'exploración-misteriosa',
    label: 'Exploración Misteriosa',
    src: '/music/exploración-misteriosa.mp3',
  },
  {
    id: 'exploración-oscura',
    label: 'Exploración Oscura',
    src: '/music/exploración-oscura.mp3',
  },
  {
    id: 'mazmorra-oscura',
    label: 'Mazmorra Oscura',
    src: '/music/mazmorra-oscura.mp3',
  },
  {
    id: 'mercado-medieval',
    label: 'Mercado Medieval',
    src: '/music/mercado-medieval.mp3',
  },
  {
    id: 'pueblo-medieval',
    label: 'Pueblo Medieval',
    src: '/music/pueblo-medieval.mp3',
  },
  {
    id: 'ruinas-antiguas',
    label: 'Ruinas Antiguas',
    src: '/music/ruinas-antiguas.mp3',
  },
  {
    id: 'taberna',
    label: 'Taberna',
    src: '/music/taberna.mp3',
  },
  {
    id: 'templo-sagrado',
    label: 'Templo Sagrado',
    src: '/music/templo-sagrado.mp3',
  },
  {
    id: 'torre-del-mago',
    label: 'Torre Del Mago',
    src: '/music/torre-del-mago.mp3',
  },
] as const;

export function getMusic(id: string): MusicDef {
  return MUSIC_TRACKS.find((m) => m.id === id) ?? MUSIC_TRACKS[0]!;
}
