import { cacheLife, cacheTag } from 'next/cache';
import type { Piece } from '@/lib/shared/types/piece.types';

/**
 * Piece use cases. Subdivisions used to share a usecase file with pieces
 * (both are global domain data); now that subdivisions are immutable
 * constants, pieces get their own file.
 */
export const pieceUseCases = {
  /**
   * Cached piece catalog. The catalog is regenerated by `pnpm gen-cat` and
   * is treated as build-time static data; `'use cache'` keeps the React
   * tree from re-serialising it on every request.
   */
  async getAllPieces(): Promise<Piece[]> {
    'use cache';
    cacheLife('hours');
    cacheTag('pathfinder:pieces');
    const { ALL_PIECES } = await import('@/assets');
    return ALL_PIECES;
  },
};