import { ALL_PIECES } from "@/assets";
import { Prisma } from "@/generated/prisma/client";
import type { PrismaClient } from "@/generated/prisma/client";
import { cacheLife, cacheTag } from "next/cache";
import type { Piece } from "@/lib/shared/types/piece.types";
import {
  DEFAULT_SUBDIVISIONS,
  type SubdivisionConfig,
  type SubdivisionConfigInput,
} from "@/lib/shared/types/subdivision.types";
import { subdivisionRepository } from "@/lib/server/db/repository/subdivision.repository";

/**
 * Subdivision use cases.
 *
 * - Cached reads take no `db` argument and import the singleton lazily.
 * - Writes accept `db` so callers control the transaction.
 * - The seed payload lives in `lib/shared/types/subdivision.types.ts` so the
 *   Prisma seed and the app-side repair path use the same source of truth.
 */
export const subdivisionUseCases = {
  /** Cached list of subdivisions ordered for the manager UI. */
  async list(): Promise<SubdivisionConfig[]> {
    "use cache";
    cacheLife("hours");
    cacheTag("pathfinder:subdivisions");
    const db = (await import("@/lib/server/db/db")).default;
    return subdivisionRepository(db).findAllOrdered();
  },

  /**
   * Cached piece catalog. The catalog is regenerated by `pnpm gen-cat` and
   * is treated as build-time static data; `'use cache'` keeps the React
   * tree from re-serialising it on every request.
   */
  async getAllPieces(): Promise<Piece[]> {
    "use cache";
    cacheLife("hours");
    cacheTag("pathfinder:pieces");
    return ALL_PIECES;
  },

  /** Create a subdivision after validating every piece id against the catalog. */
  async create(db: PrismaClient | Prisma.TransactionClient, input: SubdivisionConfigInput) {
    assertPieceIdsValid(input.pieceIds);
    return subdivisionRepository(db).create(input);
  },

  /** Update a subdivision after validating every piece id against the catalog. */
  async update(
    db: PrismaClient | Prisma.TransactionClient,
    id: string,
    input: SubdivisionConfigInput,
  ) {
    assertPieceIdsValid(input.pieceIds);
    return subdivisionRepository(db).update(id, input);
  },

  /** Delete a subdivision only when nothing references it. Throws a safe
   *  error so the action wrapper normalises it into the canonical envelope. */
  async delete(db: PrismaClient | Prisma.TransactionClient, id: string): Promise<void> {
    const inUse = await subdivisionRepository(db).isInUse(id);
    if (inUse) {
      throw new Error("Subdivision is in use");
    }
    await subdivisionRepository(db).delete(id);
  },

  /** Persist a new z-order. The repository composes a transaction. */
  async reorder(
    db: PrismaClient | Prisma.TransactionClient,
    orders: { id: string; order: number }[],
  ) {
    await subdivisionRepository(db).reorderInTx(db, orders);
  },

  /**
   * Idempotent seed payload used by `prisma/seed.ts` and by app-side repair
   * paths. No-ops when the table already has rows so it is safe to call on
   * startup.
   */
  async seedDefaults(db: PrismaClient | Prisma.TransactionClient): Promise<void> {
    const existing = await subdivisionRepository(db).findAllOrdered();
    if (existing.length > 0) return;
    for (const input of DEFAULT_SUBDIVISIONS) {
      await subdivisionRepository(db).create(input);
    }
  },
};

function assertPieceIdsValid(pieceIds: string[]): void {
  const validIds = new Set(ALL_PIECES.map((p) => p.id));
  for (const id of pieceIds) {
    if (!validIds.has(id)) {
      throw new Error(`Pieza inválida: ${id}`);
    }
  }
}