// Auto-generated by src/assets/scripts/generate-catalog.ts
// Run `pnpm gen-cat` after adding or changing textures.

import type { Texture } from "@/pieces";

export const ALL_TEXTURES: Texture[] = [
  {
    "id": "decoration-marker",
    "name": "Marker",
    "imagePath": "/pieces/textures/decoration/marker.svg",
    "width": 16,
    "height": 16,
    "category": "decoration",
    "tags": [
      "decoration"
    ]
  },
  {
    "id": "door-closed",
    "name": "Closed",
    "imagePath": "/pieces/textures/door/closed.svg",
    "width": 64,
    "height": 64,
    "category": "door",
    "tags": [
      "door"
    ]
  },
  {
    "id": "door-locked",
    "name": "Locked",
    "imagePath": "/pieces/textures/door/locked.svg",
    "width": 64,
    "height": 64,
    "category": "door",
    "tags": [
      "door"
    ]
  },
  {
    "id": "door-open",
    "name": "Open",
    "imagePath": "/pieces/textures/door/open.svg",
    "width": 64,
    "height": 64,
    "category": "door",
    "tags": [
      "door"
    ]
  },
  {
    "id": "floor-sand",
    "name": "Sand",
    "imagePath": "/pieces/textures/floor/sand.svg",
    "width": 64,
    "height": 64,
    "category": "floor",
    "tags": [
      "floor"
    ]
  },
  {
    "id": "floor-stone",
    "name": "Stone",
    "imagePath": "/pieces/textures/floor/stone.svg",
    "width": 64,
    "height": 64,
    "category": "floor",
    "tags": [
      "floor"
    ]
  },
  {
    "id": "floor-wood",
    "name": "Wood",
    "imagePath": "/pieces/textures/floor/wood.svg",
    "width": 64,
    "height": 64,
    "category": "floor",
    "tags": [
      "floor"
    ]
  },
  {
    "id": "lava-plain",
    "name": "Plain",
    "imagePath": "/pieces/textures/lava/plain.svg",
    "width": 64,
    "height": 64,
    "category": "lava",
    "tags": [
      "lava"
    ]
  },
  {
    "id": "wall-stone",
    "name": "Stone",
    "imagePath": "/pieces/textures/wall/stone.svg",
    "width": 64,
    "height": 64,
    "category": "wall",
    "tags": [
      "wall"
    ]
  },
  {
    "id": "water-plain",
    "name": "Plain",
    "imagePath": "/pieces/textures/water/plain.svg",
    "width": 64,
    "height": 64,
    "category": "water",
    "tags": [
      "water"
    ]
  }
];

export function findTexture(textureId: string): Texture | undefined {
  return ALL_TEXTURES.find((t) => t.id === textureId);
}

export function findTexturesByIds(ids: string[]): Texture[] {
  return ids
    .map((id) => findTexture(id))
    .filter((t): t is Texture => t !== undefined);
}
