// Auto-generated by src/assets/scripts/generate-catalog.ts
// Run `pnpm gen-cat` after adding or changing pieces.

import type { Piece } from "@/lib/shared/types";

export const ALL_PIECES: Piece[] = [
  {
    "id": "decoration-marker",
    "name": "Decoration Marker",
    "category": "decoration",
    "visualStates": [
      {
        "id": "default",
        "imagePath": "/pieces/textures/decoration/marker.svg",
        "isDefault": true
      }
    ],
    "width": 16,
    "height": 16,
    "tags": [
      "decoration"
    ]
  },
  {
    "id": "door",
    "name": "Door",
    "category": "door",
    "visualStates": [
      {
        "id": "closed",
        "imagePath": "/pieces/textures/door/closed.svg",
        "isDefault": true
      },
      {
        "id": "locked",
        "imagePath": "/pieces/textures/door/locked.svg"
      },
      {
        "id": "open",
        "imagePath": "/pieces/textures/door/open.svg"
      }
    ],
    "width": 64,
    "height": 64,
    "tags": [
      "door"
    ],
    "traits": [
      {
        "kind": "door-states",
        "state": "closed"
      }
    ]
  },
  {
    "id": "floor-pasto",
    "name": "Floor Pasto",
    "category": "floor",
    "visualStates": [
      {
        "id": "default",
        "imagePath": "/pieces/textures/floor/pasto.webp",
        "isDefault": true
      }
    ],
    "width": 128,
    "height": 128,
    "tags": [
      "floor"
    ]
  },
  {
    "id": "floor-sand",
    "name": "Floor Sand",
    "category": "floor",
    "visualStates": [
      {
        "id": "default",
        "imagePath": "/pieces/textures/floor/sand.svg",
        "isDefault": true
      }
    ],
    "width": 64,
    "height": 64,
    "tags": [
      "floor"
    ]
  },
  {
    "id": "floor-stone",
    "name": "Floor Stone",
    "category": "floor",
    "visualStates": [
      {
        "id": "default",
        "imagePath": "/pieces/textures/floor/stone.svg",
        "isDefault": true
      }
    ],
    "width": 64,
    "height": 64,
    "tags": [
      "floor"
    ]
  },
  {
    "id": "floor-wood",
    "name": "Floor Wood",
    "category": "floor",
    "visualStates": [
      {
        "id": "default",
        "imagePath": "/pieces/textures/floor/wood.svg",
        "isDefault": true
      }
    ],
    "width": 64,
    "height": 64,
    "tags": [
      "floor"
    ]
  },
  {
    "id": "lava-plain",
    "name": "Lava Plain",
    "category": "lava",
    "visualStates": [
      {
        "id": "default",
        "imagePath": "/pieces/textures/lava/plain.svg",
        "isDefault": true
      }
    ],
    "width": 64,
    "height": 64,
    "tags": [
      "lava"
    ]
  },
  {
    "id": "wall-azul",
    "name": "Wall Azul",
    "category": "wall",
    "visualStates": [
      {
        "id": "default",
        "imagePath": "/pieces/textures/wall/azul.webp",
        "isDefault": true
      }
    ],
    "width": 128,
    "height": 128,
    "tags": [
      "wall"
    ]
  },
  {
    "id": "wall-stone",
    "name": "Wall Stone",
    "category": "wall",
    "visualStates": [
      {
        "id": "default",
        "imagePath": "/pieces/textures/wall/stone.svg",
        "isDefault": true
      }
    ],
    "width": 64,
    "height": 64,
    "tags": [
      "wall"
    ]
  },
  {
    "id": "water-plain",
    "name": "Water Plain",
    "category": "water",
    "visualStates": [
      {
        "id": "default",
        "imagePath": "/pieces/textures/water/plain.svg",
        "isDefault": true
      }
    ],
    "width": 64,
    "height": 64,
    "tags": [
      "water"
    ]
  }
];

export function findPiece(pieceId: string): Piece | undefined {
  return ALL_PIECES.find((p) => p.id === pieceId);
}

export function findPiecesByIds(ids: string[]): Piece[] {
  return ids
    .map((id) => findPiece(id))
    .filter((p): p is Piece => p !== undefined);
}
